server:
  port: 10000
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 20MB
app:
  location: uploadpath
  python-exec: python_exec_path
  python-file: path_exifread_photo.py